#!/bin/ksh
#
# $OpenBSD: isakmpd,v 1.3 2018/01/11 21:09:26 rpe Exp $

daemon="/sbin/isakmpd"

. /etc/rc.d/rc.subr

pexp="isakmpd: monitor \[priv\]"

rc_pre() {
	if [[ ${sasyncd_flags} != NO ]]; then
		daemon_flags="-S ${daemon_flags}"
	fi
}

rc_cmd $1
